dataset:
  _target_: "examples.consec.dataset.ConsecDataset.from_samples"
  tokenizer: ${data.tokenizer}
  sense_inventory: ${data.sense_inventory}
  dependency_finder: ${data.dependency_finder}
  sentence_window: 2  # one prev one next
  randomize_sentence_window: False
  use_definition_start: ${data.use_definition_start}
  remove_multilabel_instances: False
  shuffle_definitions: False
  randomize_dependencies: False
  text_encoding_strategy: ${data.text_encoding_strategy}
  is_doc_based: True
  min_length: -1
  max_length: -1
  tokens_per_batch: 1536
  max_batch_size: 128
  section_size: 45_000
  prebatch: True
  materialize: False
  for_inference: True