dataset:
  _target_: 'classy.data.dataset.hf.HFTokenDataset.from_lines'
  transformer_model: ${transformer_model}
  min_length: -1
  max_length: -1
  tokens_per_batch: 800
  max_batch_size: -1
  section_size: 10000
  prebatch: True
  shuffle: False