callbacks:
  - _target_: "classy.pl_callbacks.prediction.PredictionPLCallback"
    prediction_confs:
      - name: "seqeval"
        path: null
        token_batch_size: 300
        limit: -1
        enabled_prediction_callbacks:
          - "file_dumper"
          - "seqeval"
    prediction_callbacks:
      file_dumper:
        _target_: "classy.pl_callbacks.prediction.FileDumperPredictionCallback"
      seqeval:
        _target_: "classy.pl_callbacks.prediction.SeqEvalPredictionCallback"
    prediction_dataset_conf: ${prediction.dataset}