callbacks:
  - _target_: "classy.pl_callbacks.prediction.PredictionPLCallback"
    prediction_confs:
      - name: "raganato"
        path: "data/wsd/jsonl/validation.jsonl"  # todo terrible hardcoded path
        token_batch_size: 300
        limit: -1
        enabled_prediction_callbacks:
          - "file_dumper"
          - "raganato"
    prediction_callbacks:
      file_dumper:
        _target_: "classy.pl_callbacks.prediction.FileDumperPredictionCallback"
      raganato:
        _target_: "examples.consec.framework_evaluation.RaganatoPredictionCallback"
        gold_key_path: "data/wsd/WSD_Evaluation_Framework/Evaluation_Datasets/semeval2007/semeval2007.gold.key.txt"  # todo terrible hardcoded path
        scorer_folder: "data/wsd/WSD_Evaluation_Framework/Evaluation_Datasets/"  # todo terrible hardcoded path
    prediction_dataset_conf: ${prediction.dataset}