callbacks:
  - _target_: "classy.pl_callbacks.prediction.PredictionPLCallback"
    prediction_confs:
      - name: "file-dumper"
        path: null  # to be set via CLI (ex: -c callbacks.callbacks.0.prediction_confs.0.path=data/europarl/validation.tsv)
        token_batch_size: 400
        prediction_param_conf_path: "configurations/prediction-params/generation-beam.yaml"
        limit: 1000
        enabled_prediction_callbacks:
          - "file_dumper"
    prediction_callbacks:
      file_dumper:
        _target_: "classy.pl_callbacks.prediction.FileDumperPredictionCallback"
    prediction_dataset_conf: ${prediction.dataset}