_target_: 'classy.models.consec.module.ConsecPLModule'
sense_extractor:
  _target_: classy.models.consec.sense_extractors.DebertaPositionalExtractor
  transformer_model: ${transformer_model}
  dropout: 0.0
  use_definitions_mask: True
optim_conf:
  _target_: classy.optim.factories.RAdamFactory
  lr: 3e-6
  weight_decay: 0.01
  no_decay_params:
    - bias
    - LayerNorm.weight
predictor:
  _target_: classy.models.consec.prediction.GreedyDepPredictor
  dependency_finder: ${data.dependency_finder}